### ISSUE TITLE
Failing to parse an http security scheme

### ISSUE THREAD

**Issue by odin-delrio** [readmeio/oas#740]
## Reproduced here
https://openap.is/validate?url=https%3A%2F%2Fapi.timetime.in%2Fv3%2Fapi-docs

<img width="516" alt="image" src="https://user-images.githubusercontent.com/9112748/226402908-0260b582-7368-4e23-a1f0-15bc0904a700.png">

[Timetime](https://www.timetime.in/) is a project of mine, it autogenerates the openApi docs by using https://springdoc.org/, a common library in the spring world for that purpose.

## The problem
It happens that even if configuring a name, spring-doc does not include that as part of the OpenApi definition for the SecurityScheme objects... but, shall it do it?
Based on the [specification](https://swagger.io/specification/), if I'm understanding this correctly, that `name` field should be only required when the `type` is set to `apiKey`. 

<img width="874" alt="image" src="https://user-images.githubusercontent.com/9112748/226404106-4b7ef844-5705-42ca-bfce-2d2c227282fe.png">

In my case, I use the type `http` so I think this validation should not fail, am I missing something? 
Thanks in advance :)

**Comment by erunion** [comment]
Hey! Our OpenAPI parser gets a bit confused sometimes because it runs [ajv](https://npm.im/ajv) validation against the OpenAPI JSON Schema definitions that the OAS group supplies. In this case they have it set up so that `bearerFormat` can only be supplied if `scheme` is `bearer`.

It's unfortunately not smart enough to do look at this as as a case-insensitive check so if you change `Bearer` to `bearer` it should work.
