### ISSUE TITLE
Question: How do you validate without derefing?

### ISSUE THREAD

**Issue by devi-prsd** [readmeio/oas#835]
I'm using oas-normalize, when I use validate and if there are any errors then the compiled error message generated has different line numbers than the provided json/yml. I'm guessing due to dereffing it expands the line numbers? Thoughts?

**Comment by erunion** [comment]
The library we use under the hood for for validation, https://github.com/APIDevTools/swagger-parser, unfortunately doesn't offer any way of doing validation _without_ first dereferencing. I believe this was an intentional design choice because it wants to also validate any external `$ref` pointers that might be pulled in.
